### ISSUE TITLE
Criar APIs que alimentarão os painéis

### ISSUE THREAD

**Issue by AliferSales** [projeto-curio/curio#3]
Para criar as visualizações dos dados que serão exibidos nos painéis, é necessário a criação de APIs para modular o acesso aos dados dos bancos dos painéis.

**Comment by fernandascovino** [comment]
Colocar uma única API por painel, que recebe os parâmetros necessários e retorna um JSON semelhante ao método figure do plotly, contendo um graphic_object para cada gráfico com seus atributos

**Comment by AliferSales** [comment]
Na verdade, a api apenas deve retornar jsons que são resultados de queries necessárias para os gráficos. Os gráficos em si serão criados no app.py, usando esses dados retornados pela api.
